require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'urcup' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  rn_maps_path = '../node_modules/react-native-maps'
   pod 'react-native-google-maps', :path => rn_maps_path
   pod 'GoogleMaps'
   pod 'Google-Maps-iOS-Utils'

  permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"

  use_react_native!(:path => config["reactNativePath"])

  target 'urcupTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'urcup-tvOS' do
  # Pods for urcup-tvOS

  target 'urcup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
